apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  namespace: mlops-fd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: fraud-model
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  namespace: mlops-fd
spec:
  selector:
    app: fraud-detection
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP